default:
  dataconnection:
    dbname: 'DB_NAME'
    host: 'DB_HOST'
    port: 5432
    user: 'DB_USER'
    password: 'DB_PASSWORD'
    
shinyapps:
  dataconnection:
    host: 'DB_HOST'
    port: 5432
    username: 'DB_USER'
    password: 'DB_PASSWORD'
