# LIST OF REQUIRED PACKAGES -----------------------------------------------
library(data.table)
library(DT)
library(rintrojs)
library(shiny)
library(shinyBS)
library(shinycssloaders)
library(shinydashboard)
library(shinyjs)
library(shinyWidgets)
library(tidyverse)
library(DBI)
library(odbc)
library(faq)
library(scales)
