name: Deploy SpliceVault Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This line allows manual triggering of the workflow

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment: test  # Specifies the GitHub Environment to use

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      
    - name: Prepare Google Analytics file
      run: |
        cp google-analytics-template.html google-analytics.html
        sed -i 's/GA_MEASUREMENT_ID/${{ vars.GA_MEASUREMENT_ID }}/g' google-analytics.html

    - name: Create version
      id: create_version
      uses: anothrNick/github-tag-action@1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        DRY_RUN: true
      
    - name: Prepare config file
      run: |
        cp config-template.yml config.yml
        sed -i 's/DB_HOST/${{ vars.DB_HOST }}/g' config.yml
        sed -i 's/DB_NAME/${{ vars.DB_NAME }}/g' config.yml
        sed -i 's/DB_USER/${{ vars.DB_USER }}/g' config.yml
        sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' config.yml

    - name: Update release candidate version
      run: |
        sed -i -e "s/RELEASE/${{ steps.create_version.outputs.tag }} RC/" ui.R
      
    - name: Deploy Shiny App
      uses: Mannyasoh/shinyapps-deploy-github-action@v1.0
      with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: ${{ vars.SHINYAPPS_APP_NAME }}
          accountName: ${{ vars.SHINYAPPS_ACCOUNT_NAME }}

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
          
          # force update if app with same name is already deployed
          forceUpdate: true