name: Deploy SpliceVault Test

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment: test  # Specifies the GitHub Environment to use

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Prepare Google Analytics file
      run: |
        cp google-analytics-template.html google-analytics.html
        sed -i 's/GA_MEASUREMENT_ID/${{ secrets.GA_MEASUREMENT_ID }}/g' google-analytics.html
        
    - name: Prepare config file
      run: |
        cp config-template.yml config.yml
        sed -i 's/DB_HOST/${{ vars.DB_HOST }}/g' config.yml
        sed -i 's/DB_NAME/${{ vars.DB_NAME }}/g' config.yml
        sed -i 's/DB_USER/${{ vars.DB_USER }}/g' config.yml
        sed -i 's/DB_PASSWORD/${{ secrets.DB_PASSWORD }}/g' config.yml

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        R -e 'install.packages("rsconnect", dependencies = TRUE)'
      
    - name: Deploy to shinyapps.io using Test environment secrets
      run: |
        R -e 'rsconnect::setAccountInfo(name="${{ vars.SHINYAPPS_ACCOUNT_NAME }}", token="${{ secrets.SHINYAPPS_TOKEN }}", secret="${{ secrets.SHINYAPPS_SECRET }}")'
        R -e 'rsconnect::deployApp(appName="${{ SHINYAPPS_APP_NAME }}", account="${{ vars.SHINYAPPS_ACCOUNT_NAME }}")'
