name: Verify redirect to prod environment

on:
  schedule:
    # Runs every day at 12:00 UTC. You can modify this as needed.
    - cron: '0 12 * * *'

jobs:
  check-redirect:
    runs-on: ubuntu-latest

    steps:
    - name: Check URL for 301 and location
      run: |
        URL_TO_CHECK="https://kidsneuro.shinyapps.io/splicevault/"
        EXPECTED_REDIRECT="https://splicevault.frontiergenomics.com.au"

        RESPONSE=$(curl -s -o /dev/null -w "%{http_code} %{redirect_url}" $URL_TO_CHECK)

        HTTP_STATUS=$(echo $RESPONSE | cut -d' ' -f1)
        REDIRECT_URL=$(echo $RESPONSE | cut -d' ' -f2)

        if [[ $HTTP_STATUS -ne 301 ]]; then
          echo "Expected HTTP 301 but got $HTTP_STATUS"
          exit 1
        fi

        if [[ $REDIRECT_URL != $EXPECTED_REDIRECT ]]; then
          echo "Expected redirect to $EXPECTED_REDIRECT but got $REDIRECT_URL"
          exit 1
        fi

        echo "All checks passed."
